--- 

    - name: Setting up base system... 
      hostname: 
        name: "{{ server_hostname }}" 
        use: systemd


    - include_tasks: update.yml 
    - include_tasks: pkgs.yml 
    - include_tasks: bash_env.yml 
    - include_tasks: sshd.yml 
    - include_tasks: firewall.yml 
